---
id: ruby-association-2022-grant-accomplishment-report
base_name: slide
tags: []
presentation_date: '2023-08-28'
presentation_start_time:
presentation_end_time:
version: 1.0.1
licenses: ['MIT']
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
source_code_uri: https://github.com/unasuke/ruby-association-2022-grant-accomplishment-report
author:
  markup_language: :markdown
  name: unasuke
  email: yusuke1994525@gmail.com
  rubygems_user: unasuke
  slideshare_user:
  speaker_deck_user:
